export const SOURCE_TYPE = {
  URL: "URL",
  TEXT: "TEXT",
  PDF: "PDF",
  YOUTUBE: "YOUTUBE",
} as const;

export type SourceType = (typeof SOURCE_TYPE)[keyof typeof SOURCE_TYPE];

export const INGESTION_STATUS = {
  INGESTED: "INGESTED",
  INITIALIZING: "INITIALIZING",
  CHUNKING: "CHUNKING",
  EMBEDDING: "EMBEDDING",
  GRAPH_BUILDING: "GRAPH_BUILDING",
  READY: "READY",
  FAILED: "FAILED",
} as const;

export type IngestionStatus =
  (typeof INGESTION_STATUS)[keyof typeof INGESTION_STATUS];

export const RELATION_TYPE = {
  RELATES_TO: "RELATES_TO",
  IS_PART_OF: "IS_PART_OF",
  DEPENDS_ON: "DEPENDS_ON",
  SIMILAR_TO: "SIMILAR_TO",
  LEADS_TO: "LEADS_TO",
  IS_PREREQUISITE_OF: "IS_PREREQUISITE_OF",
  REFERENCES: "REFERENCES",
  EXTENDS: "EXTENDS",
  CONTRADICTS: "CONTRADICTS",
  FOLLOW_UP_TO: "FOLLOW_UP_TO",
} as const;

export type RelationType = (typeof RELATION_TYPE)[keyof typeof RELATION_TYPE];

export const JOB_TYPE = {
  URL_EXTRACTION: "URL_EXTRACTION",
  CHUNKING: "CHUNKING",
  EMBEDDING: "EMBEDDING",
  CONCEPT_EXTRACTION: "CONCEPT_EXTRACTION",
  DAILY_REVIEW: "DAILY_REVIEW",
} as const;

export type JobType = (typeof JOB_TYPE)[keyof typeof JOB_TYPE];

export const LEARNING_STATUS = {
  TO_WATCH: "TO_WATCH",
  TO_READ: "TO_READ",
  UPCOMING: "UPCOMING",
  IN_PROGRESS: "IN_PROGRESS",
  REVIEW: "REVIEW",
  COMPLETED: "COMPLETED",
  PENDING_COMPLETION: "PENDING_COMPLETION",
} as const;

export type LearningStatus =
  (typeof LEARNING_STATUS)[keyof typeof LEARNING_STATUS];

export const DOCUMENT_TYPE = {
  ARTICLE: "ARTICLE",
  VIDEO: "VIDEO",
  COURSE_LESSON: "COURSE_LESSON",
  BOOK: "BOOK",
  NOTE: "NOTE",
  RFC: "RFC",
  BLOG: "BLOG",
  TRANSCRIPT: "TRANSCRIPT",
  OTHER: "OTHER",
} as const;

export type DocumentType = (typeof DOCUMENT_TYPE)[keyof typeof DOCUMENT_TYPE];

export const ANNOTATION_TYPE = {
  HIGHLIGHT: "HIGHLIGHT",
  NOTE: "NOTE",
  QUESTION: "QUESTION",
  INSIGHT: "INSIGHT",
} as const;

export type AnnotationType =
  (typeof ANNOTATION_TYPE)[keyof typeof ANNOTATION_TYPE];
